name = "HistoricalStdlibVersions"
uuid = "6df8b67a-e8a0-4029-b4b7-ac196fe72102"
authors = ["Ian <i.r.butterworth@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1.7"

[targets]
test = ["Test", "Pkg"]
